import json
from app.scripts.incremental_indexer import IncrementalFaissIndexer

def run():
    print("Generating robust synthetic medical paragraphs...")
    
    # 5 Massive Medical Cases representing realistic PMC-Patients data
    cases_data = [
        "A 68-year-old male with a significant past medical history of type 2 diabetes mellitus, essential hypertension, and hyperlipidemia presented to the emergency department complaining of an abrupt onset of severe, tearing chest pain radiating to his back. His vital signs on arrival revealed a blood pressure of 210/110 mmHg, heart rate of 115 bpm, respiratory rate of 22 breaths/min, and oxygen saturation of 98% on room air. Physical examination was notable for a decrescendo diastolic murmur at the right sternal border and an asymmetric radial pulse, with the right pulse being significantly weaker than the left. A STAT computed tomography angiography (CTA) of the chest and abdomen demonstrated an extensive Stanford Type A acute aortic dissection extending from the ascending aorta to the level of the renal arteries, with involvement of the brachiocephalic trunk. The patient was immediately started on intravenous esmolol and nitroprusside infusions for aggressive blood pressure and heart rate control. Cardiothoracic surgery was consulted urgently, and the patient was taken to the operating room for an emergent ascending aortic replacement. Post-operatively, the patient required a prolonged stay in the intensive care unit due to transient acute kidney injury and delirium but was eventually discharged to a rehabilitation facility on day 15.",
        
        "A 45-year-old female with no significant past medical history presented to the clinic complaining of progressive fatigue, generalized weakness, and sharp, pleuritic chest pain that worsened with deep inspiration and lying flat. She reported that the pain was partially relieved by sitting up and leaning forward. Two weeks prior, she had experienced a self-limiting upper respiratory tract infection characterized by a low-grade fever, rhinorrhea, and myalgias. On examination, the patient was afebrile, with a heart rate of 95 bpm and a blood pressure of 115/75 mmHg. Auscultation of the chest revealed a harsh, scratchy, high-pitched sound best heard over the left lower sternal border during end-expiration, consistent with a pericardial friction rub. An electrocardiogram (ECG) was performed, which showed widespread, concave-upwards ST-segment elevations across most limb and precordial leads, accompanied by PR-segment depressions. An echocardiogram demonstrated a small, hemodynamically insignificant pericardial effusion without evidence of cardiac tamponade. The patient was diagnosed with acute viral pericarditis. She was prescribed a course of high-dose ibuprofen and colchicine, and instructed to avoid strenuous physical activity. Upon follow-up two weeks later, her symptoms had completely resolved, and a repeat ECG showed normalization of the ST and PR segments.",
        
        "A 32-year-old previously healthy male was brought to the trauma bay via ambulance after a high-speed motor vehicle collision. The patient was the restrained driver of a vehicle that struck a concrete barrier. Primary survey revealed an intact airway, tachypnea at 28 breaths/min, and tachycardia at 125 bpm. His blood pressure was borderline at 95/60 mmHg. Secondary survey was significant for exquisite point tenderness over the right mid-clavicular region, bruising across the anterior chest wall (seatbelt sign), and diminished breath sounds over the right hemithorax. A portable anteroposterior chest radiograph demonstrated a completely opacified right hemithorax with a subtle mediastinal shift to the left, highly suspicious for a massive right-sided hemothorax. A 36-French tube thoracostomy was immediately placed in the right 5th intercostal space at the mid-axillary line, draining 1200 mL of dark red blood upon initial placement. The patient developed progressive hypotension despite aggressive fluid resuscitation with crystalloids and 2 units of uncrossmatched type O-negative packed red blood cells. Given the persistent hemodynamic instability and continued high-volume output from the chest tube (>200 mL/hr over the next two hours), the patient was taken semi-emergently to the operating room for a right anteromedial thoracotomy. Intraoperative exploration revealed an actively bleeding laceration of the right internal mammary artery, which was successfully ligated. The patient's postoperative course was relatively unremarkable, and the chest tube was removed on post-trauma day 5.",
        
        "A 72-year-old female with known paroxysmal atrial fibrillation (not on anticoagulation due to a prior gastrointestinal bleed) and mild cognitive impairment was brought to the emergency department by her family after they noticed an acute change in her behavior. Approximately two hours prior to arrival, she became suddenly aphasic and developed complete right-sided hemiplegia. A rapid neurological assessment in the ED revealed a National Institutes of Health Stroke Scale (NIHSS) score of 18, characterized by severe expressive and receptive aphasia, a right facial droop, right hemianopia, and profound weakness in the right upper and lower extremities. A non-contrast head CT showed no evidence of acute intracranial hemorrhage or early ischemic changes, while a subsequent CT angiogram (CTA) revealed a dense occlusion of the proximal left middle cerebral artery (MCA) M1 segment. Because the patient had an absolute contraindication to intravenous tissue plasminogen activator (tPA) due to her history of recent severe bleeding, the neurointerventional team was immediately mobilized. The patient underwent successful mechanical thrombectomy, achieving complete reperfusion (TICI 3 score) within 4 hours of symptom onset. Over the following days, her neurological deficits improved remarkably, and her aphasia nearly resolved. She was discharged to an acute cerebral rehabilitation center on hospital day 7 with a plan for multidisciplinary therapy and discussions regarding left atrial appendage closure.",
        
        "A 28-year-old G1P0 female at 34 weeks of gestation presented to the obstetric triage unit complaining of a severe, unrelenting frontal headache, visual disturbances described as 'flashing lights,' and right upper quadrant abdominal pain. Her prenatal course had been uncomplicated until the previous week when she noticed sudden, significant swelling in her face, hands, and feet. Upon triage evaluation, her blood pressure was markedly elevated at 185/110 mmHg on two consecutive readings taken 15 minutes apart. Urinalysis revealed 3+ proteinuria. Comprehensive metabolic panel showed elevated liver transaminases (AST 120 U/L, ALT 145 U/L) and a platelet count of 85,000/microL, raising high suspicion for HELLP (Hemolysis, Elevated Liver enzymes, Low Platelets) syndrome. The patient was immediately admitted to the labor and delivery high-dependency unit. Intravenous magnesium sulfate infusion was initiated for seizure prophylaxis, and labetalol was administered in step-wise doses to aggressively manage her severe range blood pressures. Given the severity of her condition and the high risk of maternal and fetal morbidity, a multidisciplinary decision was made to proceed with an emergent primary cesarean section. A viable female infant was delivered without complication and transferred to the NICU. The mother’s postoperative course was monitored closely; her blood pressures stabilized over the next 48 hours, and her liver enzymes and platelet counts gradually normalized by postpartum day 4."
    ]
    
    cases = []
    for idx, text in enumerate(cases_data):
        formatted = f"Clinical Case: {text}"
        cases.append({"id": f"pmc_{idx}", "text": formatted})

    print(f"Successfully generated {len(cases)} massive medical paragraphs.")
    
    indexer = IncrementalFaissIndexer()
    texts = [c["text"] for c in cases]
    print(f"Embedding and indexing {len(texts)} chunks into FAISS...")
    indexer.embed_and_add_chunk(texts)
    
    print("Saving to local JSON...")
    with open("app/data/pmc_cases.json", "w") as f:
        json.dump(cases, f)
        
    print("Complete!")

if __name__ == "__main__":
    run()
